### ISSUE TITLE
http: panic serving 127.0.0.1:xxxxx: Int64() out of bound

### ISSUE THREAD

**Issue by MatisseB** [solarlabsteam/cosmos-exporter#5] opened 2021-12-30 15:04 UTC
Hi, 
I'm facing an error on fetchhub-2 (fetch.ai)
![image](https://user-images.githubusercontent.com/37403016/147763957-f39cb892-de33-4250-b8e5-9224a096d8b7.png)

Here is the full error log:
![image](https://user-images.githubusercontent.com/37403016/147761960-e9cec2a2-8d69-490a-94d4-06ad2c1e5ae9.png)

The error comes from cosmos-sdk dependency's Int64() function:
https://github.com/cosmos/cosmos-sdk/blob/c4864e9f85011b3e971885ea995a0021c01a885d/types/int.go#L154

the function is triggered here:
https://github.com/solarlabsteam/cosmos-exporter/blob/47fc5673d3f3c1f1a465f319bfe62afb86bdc857/validator.go#L199

I've tried to find out what's happening and added some logs to check validator token values:
![image](https://user-images.githubusercontent.com/37403016/147763261-92b12352-2120-49e2-83a1-31c0a807f7db.png)
resulting with:
![image](https://user-images.githubusercontent.com/37403016/147762967-0d6359f3-de48-4759-a191-fbd7826aead8.png)

I suppose the error comes from token's absolute value: 81
I don't have much knowledge in this area. Could anyone tell me why this error occurred and if it is possible to fix it?

**Comment by Freak12Techno** [comment] 2022-01-03 00:03
Hi there. I unfortunately cannot reproduce it as I don't have the fetchai fullnode, can you try the following?
1) clone this repo
2) in validator.go, replace this part:

```
	validatorTokensGauge.With(prometheus.Labels{
		"address": validator.Validator.OperatorAddress,
		"moniker": validator.Validator.Description.Moniker,
		"denom":   Denom,
	}).Set(float64(validator.Validator.Tokens.Int64()) / DenomCoefficient)
```

with the followiing

```
	if value, err := strconv.ParseFloat(validator.Validator.Tokens.String(), 64); err != nil {
		sublogger.Error().
			Str("address", address).
			Err(err).
			Msg("Could not parse validator tokens")
	} else {
		validatorTokensGauge.With(prometheus.Labels{
			"address": validator.Validator.OperatorAddress,
			"moniker": validator.Validator.Description.Moniker,
			"denom":   Denom,
		}).Set(value / DenomCoefficient)
	}
```

3) build the binary with `go build .`, this'll produce the output at `./main`
4) try this version if it'll have the same issue

Let me know if this'll work @MatisseB

**Comment by MatisseB** [comment] 2022-01-03 11:15
Hi, thanks for the help @Freak12Techno ! 
It works for those lines of code but the same error is triggered further in validator.go at line 471 and sometimes line 576.
Maybe there is a need to change the value globally?

Output: 
![image](https://user-images.githubusercontent.com/37403016/147924480-95921d7c-5d96-46cc-b93b-284d2ea86f71.png)

**Comment by Freak12Techno** [comment] 2022-01-03 14:33
Seems like the same issue but in other places, I’ll fix it there later today as well.

**Comment by Freak12Techno** [comment] 2022-01-03 16:05
@MatisseB okay I've pushed the version that should fix at least some of these panics, can you fetch the latest changes (with the commit from today), build the exporter from it and check if it panics? if everything's okay I'll release the new version with the fix

**Comment by MatisseB** [comment] 2022-01-03 18:40
@Freak12Techno all good for me, it works like charm. 
Thanks a lot !

**Comment by Freak12Techno** [comment] 2022-01-03 19:17
Okay so I'm releasing v0.2.2 with the fix and then you can use this version instead of building it from source. I'll close this issue after that, if something like this would happen let me know.

**Comment by Freak12Techno** [comment] 2022-01-03 19:37
Done. Thanks for helping!

**Closed by Freak12Techno** 2022-01-03 19:37 UTC
